### ISSUE TITLE
Can't connect configurator to RX and indicator light issue

### ISSUE THREAD

**Issue by tabash** [openLRSng/openLRSng-configurator#17]
Hi, 

After flashing a HK OrangeRX TX and RX with firmware 3.7.0 using the new configurator (0.46) and rebinding the TX to the RX I encountered 2 issues:
1) After binding, the blue indicator light on the TX and the 2nd red light on the TX are blinking rapidly (in the past they used to be solid). The signal is passing through and the TX is moving servos at the RX but the light is blinking and not solid
2) when trying to setup the RX through the configurator (connecting the TX to the computer and connecting the TX to a power source) I get an error message from the configurator - "failed response from the RX module". I can connect to the TX perfectly fine but I can't connect to the RX

Would love any thoughts/help. Thanks in advance,

Tal

**Comment by flegmatoid** [comment]
ok, I've had similar issue - after flashing both TX & RX with OpenLRS firmware I was able to connect to receiver easily, configure it and save to EEPROM. 
After I've connected APM's telemetry port to RX UART - something broke. I was not able to connect to the receiver anymore. 
The solution with powering the RX while in RX Tab worked!!!

**Comment by kh4** [comment]
The correct sequence to connect to RX is to powercycle it while the tab is open, since the RX will only listen for config requests for some 0.5 seconds.

Immediately after reflashing with eeprom erase there is no such time limit so you can connect otherwise too.

**Comment by csurf** [comment]
@mikeller 
stale issue, please close
