### ISSUE TITLE
Info box reports incorrect receiver type

### ISSUE THREAD

**Issue by secretspy711** [openLRSng/openLRSng-configurator#21]
I flashed a Hawkeye 9-channel receiver (hardware type 3), but after connecting to it through the transmitter, the info box in the lower left part of the "RX Module" tab reports "Board: Flytron / OrangeRX 8 channel."  I'm not sure such a board actually exists, maybe it's just a simple typo and the 8 should be 9?

**Comment by kh4** [comment]
Yeah, well the OrangeRX/Flytron ones are marketed as 8ch even though they can do 9 (or actually 13 as absolute max) just like the Hawkeye one.

The board type 3 is quite overloaded since it is used for OrangeRX, Flytron and Hawkeye boards.Which from software point of view are identical.
