### ISSUE TITLE
Flytron M3 issue

### ISSUE THREAD

**Issue by stormjohn** [openLRSng/openLRSng-configurator#22]
Hi all. 
Has anyone had a similar issue with a Flytron M3 (1W) Tx as I. Having compiled the latest (March 2015) 3.8 firmware onto the Tx (I also tried V3.6.4) and set it up for UK legal 458MHz band with 6 hops. However even with a Diamond SRH771 antenna on the Tx I lose total communication with the Rx (V2 compiled the same) almost as soon as they link (intermittent "Blue" LED then solid "Red"). I have also tried it at 433MHz with the same result. Unbelievably I get the best results with a 50 Ohm "dummy load" on the Tx (over 50 meters solid blue LED and control). As soon as I put an antenna of any kind on the Tx it fails as above. I have tested it on a Power / SWR meter  and although it's a M3 (1W) the best I am achieving is 150mW (>21dbi) with the "dummy load". As a test I made up an Omni pole which achieved the 150mW at 1.1:1 SWR (Very good) but the antenna length suggests the frequency is over 500MHz.I 
Thanks in advance 
Lyn.

**Comment by csurf** [comment]
@stormjohn if you're still having hardware issues, please post them over at RC groups OpenLRSng thread:
https://www.rcgroups.com/forums/showthread.php?1782034-OpenLRS-new-firmware-fork-openLRSng

@mikeller unrelated to configurator, close
