### ISSUE TITLE
mistake values on openLRSng-configurator/js/data_storage.js ???

### ISSUE THREAD

**Issue by njozsef** [openLRSng/openLRSng-configurator#26]
Hi developers.

i think maybe improper value on initializeFrequencyLimits() function
868 and 915 type modules

frequencyLimits.minBeacon = 413000000;

best regards
Jozsef

**Comment by kh4** [comment]
Well, it is partly intentional; someone may want to use beacon on 433 band even though RC is higher, naturally this may not be optimal nor very healthy for the RFM but in case plane is in middle of woods...

**Comment by csurf** [comment]
@mikeller close
