### ISSUE TITLE
Having v0.57 but it says it's old

### ISSUE THREAD

**Issue by jsystem** [openLRSng/openLRSng-configurator#31]
Hi,

"16:50:24 -- Running - OS: Windows, Chrome: 53.0.2785.143, Configurator: 0.57
16:50:24 -- You're using an old version of openLRSng - Configurator. Please update so you can benefit from recently added features and bugfixes."
As far a I know 0.57 is the latest so seems to be a low prio bug or?

thanks,
Kornel

**Comment by gweep** [comment]
Me too!

**Comment by csurf** [comment]
@jsystem @gweep 
this will all be sorted out as this repo gets cleaned up & updated (people are actually working on it now)... Just check back in occasionally...

@mikeller, close...
