### ISSUE TITLE
TX problem

### ISSUE THREAD

**Issue by yu1s** [openLRSng/openLRSng-configurator#33]
https://www.youtube.com/watch?v=CNVOsXIO5fk&t=6s

**Comment by csurf** [comment]
@yu1s, open up the USB com port using a terminal emulator (putty, tera term, or 'serial monitor' in Arduino IDE). Post a video of what you see...

**Comment by csurf** [comment]
@yu1s 
also, power the module up with external power (battery or radio). Don't use the power supplied by the FTDI adapter. Try that...

**Comment by csurf** [comment]
user responded via youtube saying the problem was the FTDI adapter. problem solved. closed
