### ISSUE TITLE
RX Failsafe settings aren't backed up to file

### ISSUE THREAD

**Issue by csurf** [openLRSng/openLRSng-configurator#50]
Currently, only the main settings are saved, while the failsafe settings are ignored when using the 'Backup this Configuration' button within the RX tab.

@mikeller 
what's your opinion on this?
Should the failsafe settings be backed up to file along with the rest of the RX configuration?

**Comment by mikeller** [comment]
@csurf: I think that is what the user expects to happen. (i.e. a backup is a full backup), so yes, it should be done.
